
package in.omkar.modal;
// default package
// Generated Jun 11, 2024, 12:33:48 PM by Hibernate Tools 5.6.15.Final

/**
 * Bankaccount generated by hbm2java
 */
public class Bankaccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int accno;
	private String holderName;
	private Float balance;
	private String status;

	public Bankaccount() {
	}

	public Bankaccount(int accno) {
		this.accno = accno;
	}

	public Bankaccount(int accno, String holderName, Float balance, String status) {
		this.accno = accno;
		this.holderName = holderName;
		this.balance = balance;
		this.status = status;
	}

	public int getAccno() {
		return this.accno;
	}

	public void setAccno(int accno) {
		this.accno = accno;
	}

	public String getHolderName() {
		return this.holderName;
	}

	public void setHolderName(String holderName) {
		this.holderName = holderName;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
